version: "3.9"

services:
  nginx:
    image: nginx:stable
    ports:
      - "8069:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - odoo
    restart: unless-stopped

  odoo:
    image: odoo:19.0
    environment:
      - HOST=${DB_HOST}
      - PORT=${DB_PORT}
      - USER=${DB_USER}
      - PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    ports:
      - "8070:8069"
      - "8072:8072"
    volumes:
      - ./addons:/mnt/extra-addons
      - ./data/filestore:/var/lib/odoo
      - ./config/odoo.conf:/etc/odoo/odoo.conf:ro
    command: >
      odoo -d ${DB_NAME} 
           --db_host=${DB_HOST}
           --db_user=${DB_USER} 
           --db_password=${DB_PASSWORD} 
           --init=base
    restart: unless-stopped
